task_to_sample_weight_1 = {
    'eli5': 1,
    'hotpot_qa': 1,
    'fever': 1,
    'msmarco_passage': 1,
    'msmarco_document': 1,
    'nq': 1,
    'squad': 1,
    'triviaqa': 1,
    'quora_duplicate': 1, # 以前是0.2，因为没有提前采样本，现在为了方便跑pipeline，就提前把数据采样好了
    'agnews': 1,
    'amazon_qa': 1,
    'amazon_review': 1,
    'ccnews_title_text': 1,
    'gooaq_pairs': 1,
    'medmcqa': 1,
    'npr': 1,
    'paq_pairs': 1,
    's2orc_title_abstract': 1,
    'simple_wiki': 1,
    'wikihow': 1,
    'xsum': 1,
    'yahoo_answers_title_answer': 1,
    'zero_shot_re': 1,
    'synthetic': 1,
    'fiqa': 1,
}