task_to_query_type = {
    'eli5': 'user question',
    'hotpot_qa': 'multi-hop question',
    'fever': 'claim',
    'msmarco_passage': 'web search query',
    'msmarco_document': 'web search query',
    'nq': 'question',
    'squad': 'question',
    'triviaqa': 'question',
    'quora_duplicate': 'question',
    'agnews': 'news title',
    'amazon_qa': 'user question',
    'amazon_review': 'title',
    'ccnews_title_text': 'news title',
    'gooaq_pairs': 'user question',
    'medmcqa': 'medical question',
    'npr': 'news title',
    'paq_pairs': 'question',
    's2orc_title_abstract': 'paper title',
    'simple_wiki': 'Wikipedia sentence',
    'wikihow': 'Wikipedia summary',
    'xsum': 'news summary',
    'yahoo_answers_title_answer': 'question',
    'zero_shot_re': 'Wikipedia question',
}

task_to_passage_type = {
    'eli5': 'answers',
    'hotpot_qa': 'supporting documents',
    'fever': 'documents that support or refute the claim',
    'msmarco_passage': 'relevant passages that answer the query',
    'msmarco_document': 'relevant documents that answer the query',
    'nq': 'Wikipedia passages that answer the question',
    'squad': 'Wikipedia passages that answer the question',
    'triviaqa': 'Wikipedia passages that answer the question',
    'quora_duplicate': 'questions that have the same meaning as the question',
    'agnews': 'news articles that support the news title',
    'amazon_qa': 'reviews that answer the question',
    'amazon_review': 'reviews relevant to the title',
    'ccnews_title_text': 'news articles that support the news title',
    'gooaq_pairs': 'answers',
    'medmcqa': 'answers',
    'npr': 'news articles that support the news title',
    'paq_pairs': 'documents that answer the question',
    's2orc_title_abstract': 'papaer abstract revelant to the paper title',
    'simple_wiki': 'simplified Wikipedia sentences aligning to the given Wikipedia sentence',
    'wikihow': 'Wikipedia passages that enrich the Wikipedia summary',
    'xsum': 'news articles that enrich the news summary',
    'yahoo_answers_title_answer': 'answers',
    'zero_shot_re': 'Wikipedia sentences that answer the Wikipedia question',
}